[package]
name = "prs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.30.4"

anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }

procfs = { version = "0.15.1", features = ["serde1"] }

# serde = "1.0.158"
duct = "0.13.6"
cached = "0.40.0"

tracing = "0.1"
tracing-subscriber = "0.3"