[package]
name = "prs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# easier dev
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }

# core
procfs = { version = "0.15.1", features = ["serde1"] }
sqlite = "0.30.4"

# faster syscalls
duct = "0.13.6"
cached = "0.42.0"

# observability
tracing = "0.1"
tracing-subscriber = "0.3"
