[package]
name = "prs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = "4.1.13"

procfs = {version = "0.15.1", features = ["serde1"]}

rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = "1.0.158"

serde_derive = "1.0.158"
serde_rusqlite = "0.31.0"
