name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build optimized binary
        run: make docker_build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ./prs
          body: |
            ## Release ${{ github.ref_name }}
            
            Statically linked binary for x86_64 Linux (GLIBC 2.17+)
            
            ### Usage
            ```bash
            chmod +x prs
            ./prs -p top10-mem
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}